import threading
import time
import random
from datetime import datetime, timedelta
from database import get_db

def run_scheduler_cycle():
    """Checks recurring task frequency rules and generates new tasks & sensor telemetry."""
    try:
        conn = get_db()
        cursor = conn.cursor()
        now = datetime.now()
        today_str = now.strftime("%Y-%m-%d")
        now_ts = now.strftime("%Y-%m-%d %H:%M:%S")

        # 1. Update IoT Sensor Telemetry (simulate live readings)
        cursor.execute("SELECT id, name FROM zones")
        zones = cursor.fetchall()
        for zone in zones:
            zone_id = zone['id']
            # Fetch last reading
            cursor.execute("SELECT soil_moisture, humidity, temperature FROM sensor_readings WHERE zone_id = ? ORDER BY id DESC LIMIT 1", (zone_id,))
            last_reading = cursor.fetchone()
            if last_reading:
                prev_moisture = last_reading['soil_moisture']
                prev_hum = last_reading['humidity']
                prev_temp = last_reading['temperature']
            else:
                prev_moisture, prev_hum, prev_temp = 45.0, 60.0, 26.0

            # Fluctuate slightly
            new_moisture = max(18.0, min(85.0, round(prev_moisture + random.uniform(-2.5, 1.8), 1)))
            new_hum = max(40.0, min(85.0, round(prev_hum + random.uniform(-1.5, 1.5), 1)))
            new_temp = max(22.0, min(36.0, round(prev_temp + random.uniform(-0.8, 0.8), 1)))

            status_alert = "Normal"
            if new_moisture < 30.0:
                status_alert = "Low Soil Moisture – Watering Recommended"
                # Add notification if not already notified recently
                cursor.execute("""
                INSERT INTO notifications (user_id, message, type, read_status, created_at)
                SELECT 1, ?, 'Critical', 0, ?
                WHERE NOT EXISTS (
                    SELECT 1 FROM notifications 
                    WHERE message LIKE ? AND read_status = 0
                )
                """, (f"Zone '{zone['name']}' soil moisture is LOW ({new_moisture}%)! Trigger smart irrigation.", now_ts, f"%Zone '{zone['name']}'%"))

            cursor.execute("""
            INSERT INTO sensor_readings (zone_id, soil_moisture, humidity, temperature, timestamp, status_alert)
            VALUES (?, ?, ?, ?, ?, ?)
            """, (zone_id, new_moisture, new_hum, new_temp, now_ts, status_alert))

        # 2. Process Auto-Scheduler Rules for Tasks
        cursor.execute("SELECT * FROM scheduler_config WHERE auto_enabled = 1")
        configs = cursor.fetchall()

        for config in configs:
            task_type = config['task_type']
            freq_days = config['frequency_days']
            last_run = config['last_run']

            should_run = False
            if not last_run:
                should_run = True
            else:
                last_dt = datetime.strptime(last_run, "%Y-%m-%d")
                if (now - last_dt).days >= freq_days:
                    should_run = True

            if should_run:
                # Find plants needing this task
                cursor.execute("""
                SELECT p.id, p.name, p.zone_id FROM plants p
                WHERE p.id NOT IN (
                    SELECT plant_id FROM maintenance_tasks 
                    WHERE task_type = ? AND status IN ('Pending', 'In Progress') AND plant_id IS NOT NULL
                ) LIMIT 2
                """, (task_type,))
                plants_to_assign = cursor.fetchall()

                for plant in plants_to_assign:
                    staff_assigned = "Rajesh Kumar" if random.random() > 0.5 else "Sarah Jenkins"
                    priority = "High" if task_type == 'Watering' else "Medium"
                    cursor.execute("""
                    INSERT INTO maintenance_tasks 
                    (plant_id, zone_id, task_type, assigned_to, scheduled_date, status, priority, notes, created_by)
                    VALUES (?, ?, ?, ?, ?, 'Pending', ?, ?, 'Auto-Scheduler')
                    """, (plant['id'], plant['zone_id'], task_type, staff_assigned, today_str, priority, f"Automated {task_type.lower()} task generated by campus scheduler."))

                cursor.execute("UPDATE scheduler_config SET last_run = ? WHERE task_type = ?", (today_str, task_type))

        conn.commit()
        conn.close()
    except Exception as e:
        print("Scheduler cycle error:", e)

def start_background_scheduler(interval_seconds=30):
    def loop():
        while True:
            run_scheduler_cycle()
            time.sleep(interval_seconds)

    thread = threading.Thread(target=loop, daemon=True)
    thread.start()
    print(f"Background scheduler started with {interval_seconds}s interval.")
